name: Hands-on 2
on: pull_request
jobs:
  slack_notify:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_CHANNEL: '#mk-qa-random'
      SLACK_MESSAGE: 'Message for test'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Send slack message
        run: bash .github/scripts/slack_notify.sh
